// Hand-authored seed questions for the CCAO-F question bank.
// Original scenario-based items written to the public CCAO-F blueprint — NOT
// real or leaked Anthropic exam content. See CLAUDE.md for the blueprint.
import type { ItemType } from "../types.js";

export interface SeedQuestion {
  domain: number;
  itemType: ItemType;
  stem: string;
  options: { id: string; text: string }[];
  correctOptionIds: string[];
  explanation: string;
}

const opts = (texts: string[]) =>
  texts.map((text, i) => ({ id: String.fromCharCode(97 + i), text }));

export const seedQuestions: SeedQuestion[] = [
  // ───────────────────────── Domain 1: Prompting and Task Execution (12) ─────────────────────────
  {
    domain: 1,
    itemType: "single",
    stem: "A marketing associate asks Claude to 'write a product description' and gets a generic, unusable paragraph. What's the most effective way to improve the next prompt?",
    options: opts([
      "Add specifics: target audience, tone, desired length, and a couple of example phrases they like",
      "Repeat the same prompt again, since Claude's outputs vary randomly between runs",
      "Ask Claude to 'try harder' and 'be more creative' without adding new information",
      "Switch to a larger, more expensive model without changing the prompt",
    ]),
    correctOptionIds: ["a"],
    explanation: "Vague prompts produce vague outputs. Supplying audience, tone, length, and concrete examples gives Claude the context it needs to produce a usable draft — a model upgrade or a repeated identical prompt won't fix missing context.",
  },
  {
    domain: 1,
    itemType: "single",
    stem: "An operations manager needs Claude to reorganize a 40-page vendor contract, flag risky clauses, and draft a summary memo — all in one pass. The first attempt produces a shallow, incomplete result. What should they try next?",
    options: opts([
      "Decompose the task into sequential steps: first extract clauses, then flag risks, then draft the memo from the flagged list",
      "Ask for the exact same three-part request again, since Claude needs multiple identical attempts to succeed",
      "Shorten the request to just 'summarize this contract' and drop the risk-flagging requirement entirely",
      "Paste the contract twice in the same prompt so Claude reads it more carefully",
    ]),
    correctOptionIds: ["a"],
    explanation: "Task decomposition — breaking a multi-step request into sequential subtasks — produces more reliable results than asking for several distinct deliverables in a single pass, especially over long source material.",
  },
  {
    domain: 1,
    itemType: "single",
    stem: "A first draft from Claude is on-topic but too generic. What is the most effective way to iterate toward a better result?",
    options: opts([
      "Give specific feedback on what's wrong and what should change, referencing the draft directly",
      "Start a brand-new conversation with the exact same original prompt",
      "Accept the draft as final since Claude's first output is typically its best possible output",
      "Ask Claude to 'regenerate' with no additional guidance",
    ]),
    correctOptionIds: ["a"],
    explanation: "Effective iteration means giving targeted feedback referencing the actual draft ('the tone is too formal, shorten section 2') rather than re-running the same prompt or asking for a regeneration with no new signal.",
  },
  {
    domain: 1,
    itemType: "multi",
    stem: "A data analyst is prompting Claude to analyze a sales dataset. Which two additions would most improve the effectiveness of the prompt? (Select 2)",
    options: opts([
      "Specify the exact output format needed (e.g., a table with columns for region, trend, and recommendation)",
      "State the role/context: e.g., 'You're helping a regional sales director spot underperforming territories'",
      "Use as much technical statistics jargon as possible regardless of who will read the output",
      "Make the prompt as long as possible by repeating the same instruction in different words",
    ]),
    correctOptionIds: ["a", "b"],
    explanation: "Specifying desired output format and framing role/context are both well-established techniques for improving prompt effectiveness. Jargon mismatched to the audience and redundant repetition don't add useful signal.",
  },
  {
    domain: 1,
    itemType: "single",
    stem: "A team lead wants Claude to brainstorm 15 possible names for a new internal tool. How should the prompting strategy differ from a drafting task like writing a status update?",
    options: opts([
      "Ask for a wide, diverse set of options with minimal constraints on format, since breadth matters more than polish at this stage",
      "Specify one exact final answer format up front, since brainstorming needs the same precision as final drafts",
      "Give Claude a single example and ask it to produce only variations extremely close to that example",
      "Treat it identically to a drafting task — the prompting approach doesn't need to change by task type",
    ]),
    correctOptionIds: ["a"],
    explanation: "Brainstorming benefits from a prompt that encourages breadth and diversity over polish, in contrast to drafting tasks where format, tone, and precision matter more from the start.",
  },
  {
    domain: 1,
    itemType: "single",
    stem: "A researcher asks Claude to answer a factual question about a niche regulatory topic. What's the best prompting practice to support a research task like this?",
    options: opts([
      "Ask Claude to explain its reasoning and note where it's uncertain, so the answer can be verified before use",
      "Ask for a single confident-sounding sentence with no explanation, since brevity is always best for research",
      "Avoid asking Claude to flag uncertainty, since doing so makes outputs look less trustworthy",
      "Request the answer in a foreign language to reduce the chance of factual errors",
    ]),
    correctOptionIds: ["a"],
    explanation: "For research-style tasks, prompting for reasoning and explicit uncertainty flags supports the fact-checking step that should follow — a bare confident answer is harder to verify and more likely to be trusted uncritically.",
  },
  {
    domain: 1,
    itemType: "single",
    stem: "A financial analyst wants Claude to summarize a 20-page earnings report, specifically highlighting liquidity risk. Which prompt is most likely to produce a useful result?",
    options: opts([
      "\"Summarize this report in under 300 words, focusing specifically on liquidity risk factors and citing the relevant section for each\"",
      "\"Summarize this.\"",
      "\"Tell me everything about this report\"",
      "\"Is this report good or bad?\"",

    ]),
    correctOptionIds: ["a"],
    explanation: "A prompt that states the desired length, the specific focus area, and a request to cite sections gives Claude a concrete, checkable target — vague prompts like 'summarize this' leave the focus and format undefined.",
  },
  {
    domain: 1,
    itemType: "multi",
    stem: "An HR specialist is decomposing the task 'create a new-hire onboarding guide' into subtasks for Claude. Which two are reasonable decomposition steps? (Select 2)",
    options: opts([
      "First, ask Claude to outline the sections an onboarding guide typically needs",
      "Then, ask Claude to draft each section using the agreed outline as context",
      "Ask Claude to write the entire 15-page guide and the internal approval email in the same response with no structure given",
      "Skip outlining and ask Claude to guess what sections HR wants without any input",
    ]),
    correctOptionIds: ["a", "b"],
    explanation: "Good task decomposition moves from structure (outline) to content (drafting each section with that outline as context), rather than requesting an unscoped, unstructured mega-response.",
  },
  {
    domain: 1,
    itemType: "single",
    stem: "Claude's output uses a tone that's far more casual than the company's brand voice. What's the most effective next step?",
    options: opts([
      "Provide a short example of the desired tone (a few-shot example) and ask Claude to match it",
      "Give up on prompting and manually rewrite every future draft from scratch",
      "Repeat the identical prompt, since tone is not something a prompt can influence",
      "Ask Claude to use more exclamation points, assuming that alone fixes tone mismatches",
    ]),
    correctOptionIds: ["a"],
    explanation: "Providing a concrete example of the desired tone (a few-shot example) is one of the most reliable ways to steer style and voice — tone is very much influenced by prompting.",
  },
  {
    domain: 1,
    itemType: "single",
    stem: "A project manager needs Claude for two different tasks today: drafting a client email, and analyzing a spreadsheet of project delays. How should their approach differ?",
    options: opts([
      "Use a natural, audience-aware tone and structure for the email; use a structured, data-grounded prompt with the actual data attached for the analysis",
      "Use the exact same prompt template word-for-word for both tasks, since Claude adapts automatically to any wording",
      "Only attach data for the email and skip it for the analysis, since Claude can infer spreadsheet contents",
      "Avoid giving any context in either case, since extra context degrades output quality",
    ]),
    correctOptionIds: ["a"],
    explanation: "Different task types call for different prompting strategies — an email benefits from tone/audience framing, while a data-analysis task benefits from structure and the actual source data being provided, not inferred.",
  },
  {
    domain: 1,
    itemType: "single",
    stem: "An employee tells Claude, \"make it better\" after a lackluster draft. Claude's revision still misses the mark. What is the underlying prompting mistake?",
    options: opts([
      "The feedback was too vague — it didn't specify what 'better' means (tone, length, structure, content gaps)",
      "Claude cannot revise text under any circumstances",
      "The employee should have started an entirely new account instead of continuing the conversation",
      "Iteration is not a supported way to work with Claude",
    ]),
    correctOptionIds: ["a"],
    explanation: "\"Make it better\" gives no actionable signal. Effective iteration requires specific feedback about what dimension needs to change and how.",
  },
  {
    domain: 1,
    itemType: "single",
    stem: "A user is refining a prompt for a recurring weekly report. After several iterations, they've found wording that reliably produces the format they need. What should they do to make future weeks easier?",
    options: opts([
      "Save the refined prompt as a reusable template and adjust only the data/date fields going forward",
      "Discard the refined prompt each week and start from a blank prompt to keep things 'fresh'",
      "Manually rewrite the whole report themselves going forward instead of reusing the working prompt",
      "Make the prompt more vague each week so Claude has to guess the format",
    ]),
    correctOptionIds: ["a"],
    explanation: "Once a prompt is proven to reliably produce the desired output, reusing it as a template (with only variable content swapped) is the efficient approach — this is a core part of effective, repeatable prompting.",
  },

  // ───────────────────────── Domain 2: Output Evaluation and Validation (18) ─────────────────────────
  {
    domain: 2,
    itemType: "single",
    stem: "Claude produces a market analysis that cites a statistic — '43% of enterprises adopted AI tools in 2019' — attributed to a named research firm. The employee doesn't recognize the source. What should they do before using this figure in a client deck?",
    options: opts([
      "Independently verify the statistic and its source before including it, since Claude can generate plausible-sounding but incorrect citations",
      "Include it as-is, since Claude only produces verified statistics",
      "Remove all numbers from Claude's output permanently, since AI tools can never be trusted with data",
      "Change the number slightly so it looks less suspicious without checking whether it's accurate",
    ]),
    correctOptionIds: ["a"],
    explanation: "This is a classic hallucination risk — a specific, confident-sounding citation should be fact-checked before it's used externally, not assumed accurate or blindly altered.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "An analyst asks Claude to compare two quarters of revenue data. Claude's summary states Q2 revenue 'grew' while the pasted table actually shows a decline. What kind of issue is this?",
    options: opts([
      "An inconsistency between the output and the source data that must be caught before the summary is used",
      "A normal and expected part of AI-generated summaries that doesn't need review",
      "Evidence that the underlying data table itself must be wrong",
      "A formatting issue only, with no bearing on the summary's accuracy",
    ]),
    correctOptionIds: ["a"],
    explanation: "When an output contradicts the source material it was supposedly built from, that's a factual inconsistency — a core thing to check for during output evaluation, not something to wave off as expected behavior.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "Claude drafts a hiring rubric that consistently favors candidates from a specific university mentioned in the example prompt. What should the reviewer be alert to?",
    options: opts([
      "Potential bias introduced by the prompt's framing or training patterns, which should be corrected before the rubric is used",
      "Nothing — hiring rubrics are objective by definition once Claude generates them",
      "A hallucination, since bias and hallucination are the same issue",
      "A formatting bug that can be fixed by changing the font",
    ]),
    correctOptionIds: ["a"],
    explanation: "Recognizing bias in outputs — even subtle framing effects — is a distinct evaluation skill from catching hallucinations. Biased criteria in something like a hiring rubric need explicit correction before use.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "A legal assistant is using Claude to draft language for a contract clause with real regulatory consequences. What's the appropriate level of human review?",
    options: opts([
      "A qualified human (e.g., legal counsel) should review the draft before it's used, given the high stakes and specialized domain",
      "No review is needed since Claude's legal drafts are pre-vetted by regulators",
      "Only a spell-check is needed",
      "Review is only needed if the clause is longer than one paragraph",
    ]),
    correctOptionIds: ["a"],
    explanation: "Deciding when human review is required is part of output evaluation — high-stakes, regulated, or specialized content (like binding legal language) warrants qualified human review before use, regardless of how polished the draft looks.",
  },
  {
    domain: 2,
    itemType: "multi",
    stem: "Which two of the following are effective fact-checking practices when reviewing a Claude-generated research summary? (Select 2)",
    options: opts([
      "Cross-reference specific factual claims and numbers against a trusted primary source",
      "Check whether cited sources actually exist and say what the summary claims they say",
      "Assume accuracy because the summary reads fluently and confidently",
      "Assume accuracy because the summary is long and detailed",
    ]),
    correctOptionIds: ["a", "b"],
    explanation: "Fluency, confidence, and length are not reliable signals of accuracy. Actually cross-referencing claims and verifying that cited sources exist and say what's claimed are the real fact-checking steps.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "A support team lead asks Claude to draft a customer-facing response and an internal Slack summary of the same incident. Which best describes how to adapt these for their respective audiences?",
    options: opts([
      "Edit the customer-facing version for a more formal, reassuring tone and the internal version for brevity and technical detail",
      "Use the exact same wording for both since the underlying facts are identical",
      "Make the internal Slack summary more formal than the customer-facing message",
      "Skip editing entirely since Claude's first draft is already audience-appropriate for both",
    ]),
    correctOptionIds: ["a"],
    explanation: "Editing and adapting outputs for the intended audience — different tone and detail level for customers vs. internal teams — is a key output-evaluation skill, even when the underlying facts don't change.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "An education content designer needs to produce an interactive worksheet with fill-in fields plus a summary explanation for teachers. Which output format choice fits best?",
    options: opts([
      "Use an artifact for the interactive worksheet and inline chat text for the teacher-facing explanation",
      "Put everything, including the interactive worksheet, only in plain inline chat text",
      "Always use structured data (e.g., raw JSON) regardless of who will read or use it",
      "Avoid artifacts entirely since they can't contain structured or interactive content",
    ]),
    correctOptionIds: ["a"],
    explanation: "Picking the right output format is part of curating and evaluating outputs — artifacts suit standalone, reusable, or interactive content, while inline chat text suits conversational explanations.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "Claude gives two contradictory answers to the same factual question asked twice in the same conversation, worded slightly differently each time. What should the user conclude?",
    options: opts([
      "This inconsistency is a signal to verify the claim externally before trusting either answer",
      "The second answer is automatically the correct one",
      "The first answer is automatically the correct one",
      "Contradictions like this never happen and the user must have misread one of the answers",
    ]),
    correctOptionIds: ["a"],
    explanation: "Internal inconsistency across responses is itself a red flag worth investigating — it doesn't tell you which answer (if either) is correct, only that independent verification is warranted.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "A nonprofit uses Claude to draft a grant report. The draft cites a specific line of a funder's guidelines that, on inspection, doesn't actually exist in the guidelines document. What is this an example of?",
    options: opts([
      "A hallucination — a fabricated but plausible-sounding detail that must be caught before submission",
      "A normal citation style that doesn't require the actual guideline to exist",
      "Evidence the funder's guidelines document is incomplete",
      "A sign that Claude accessed a newer version of the guidelines the user doesn't have",
    ]),
    correctOptionIds: ["a"],
    explanation: "A specific, invented reference to a document that doesn't contain it is a textbook hallucination — always worth checking against the primary source before it goes into anything submitted externally.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "A user asks Claude to compare three vendor proposals and pick the best one for a six-figure contract. What is the most appropriate way to use Claude's recommendation?",
    options: opts([
      "Treat it as one input among several, and have a qualified decision-maker validate the reasoning before committing to the contract",
      "Sign the contract with the recommended vendor immediately, since Claude's analysis is authoritative",
      "Ignore Claude's analysis entirely since AI tools should never assist with vendor decisions",
      "Ask Claude to sign the contract on the company's behalf to save time",
    ]),
    correctOptionIds: ["a"],
    explanation: "For consequential decisions, Claude's output should inform — not replace — human judgment and validation, especially where financial commitments are involved.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "Reviewing a Claude-generated summary of customer feedback, an analyst notices the summary emphasizes only positive comments even though the raw data was roughly half negative. What should they check for?",
    options: opts([
      "Whether the prompt or sampling process introduced a skew, and correct the summary for completeness/balance",
      "Nothing — summaries are always allowed to selectively favor certain results",
      "Whether the negative comments were fake, since Claude wouldn't omit real data",
      "Whether the customer feedback tool itself is broken",
    ]),
    correctOptionIds: ["a"],
    explanation: "An unbalanced summary relative to the source data is a completeness/bias issue to catch during evaluation — the fix is checking the prompt and source data, not assuming the omitted data was invalid.",
  },
  {
    domain: 2,
    itemType: "multi",
    stem: "A user is deciding whether a Claude output needs human review before being sent externally. Which two factors should weigh most heavily toward requiring review? (Select 2)",
    options: opts([
      "The content will be seen by customers, regulators, or the public",
      "The content involves numbers, legal claims, or commitments that could cause harm if wrong",
      "The content is only for the user's own private notes and will never be shared",
      "The draft happens to be under 100 words",
    ]),
    correctOptionIds: ["a", "b"],
    explanation: "External visibility and real-world consequences (financial, legal, safety) are the key drivers for requiring human review — private notes and word count aren't meaningful risk signals.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "Claude produces a well-organized table comparing five competitor products with pricing. Before circulating it, what is the most important accuracy check?",
    options: opts([
      "Verify the pricing and feature figures against each competitor's actual current source (site, sheet, or filing)",
      "Check only that the table's formatting looks clean and professional",
      "Ensure all five competitor names are spelled with consistent capitalization",
      "No check is necessary since tables are inherently more accurate than prose",
    ]),
    correctOptionIds: ["a"],
    explanation: "Formatting polish is not a substitute for factual accuracy — competitive pricing data should be checked against real current sources before it's circulated, since it can easily be stale or fabricated.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "An operations lead asks Claude to identify 'inconsistencies' in a shipping log. What is Claude most likely being asked to find?",
    options: opts([
      "Entries that contradict each other or don't match expected patterns (e.g., a delivery dated before its shipment date)",
      "Typos only, with no attention to the actual data values",
      "Only entries written in a different font",
      "Entries that are simply the longest in the log",
    ]),
    correctOptionIds: ["a"],
    explanation: "Identifying inconsistencies means finding data that contradicts itself or violates expected logic (like a delivery date preceding its ship date) — a core output-evaluation skill applied to structured data.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "A user wants Claude's help curating the most relevant findings from a 50-page research report into a one-page executive brief. What does 'curation' mean in this context?",
    options: opts([
      "Selecting and prioritizing the most decision-relevant points rather than including everything",
      "Copying the entire report verbatim with no changes",
      "Removing all numbers and specific facts to make it shorter",
      "Rewriting the report in a different language only",
    ]),
    correctOptionIds: ["a"],
    explanation: "Curation is about selecting and prioritizing what matters most for the audience and purpose — not indiscriminately shortening or copying content wholesale.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "Claude's answer to a technical support question sounds confident and detailed but conflicts with the product's official documentation. What should the support rep do?",
    options: opts([
      "Defer to the official documentation and flag or correct the discrepancy rather than trusting confident tone alone",
      "Trust Claude's answer because it's more detailed than the documentation",
      "Send both answers to the customer and let them decide which is correct",
      "Escalate to delete the official documentation since it must be outdated",
    ]),
    correctOptionIds: ["a"],
    explanation: "Confidence and detail in an AI-generated answer are not proof of accuracy. When a Claude output conflicts with an authoritative source, the authoritative source should generally win, and the conflict should be investigated.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "A user asks Claude to produce a dataset of \"top 10 competitors' 2025 revenue figures.\" Several numbers look suspiciously round and no sources are cited. What's the appropriate response?",
    options: opts([
      "Treat the figures as unverified and require sourcing/verification before using them anywhere external",
      "Publish the figures immediately since round numbers are usually more trustworthy",
      "Assume the numbers are accurate because the request was specific",
      "Ask Claude to make the numbers less round so they look more believable",
    ]),
    correctOptionIds: ["a"],
    explanation: "Suspiciously round, uncited figures for something like competitor revenue are a common hallucination pattern — they need verification, not cosmetic adjustment to look more convincing.",
  },
  {
    domain: 2,
    itemType: "single",
    stem: "A user wants a quick way to compare two Claude drafts of the same press release side by side before choosing one. What's a reasonable approach?",
    options: opts([
      "Ask Claude to summarize the key differences between the two drafts, then read both critically before deciding",
      "Flip a coin, since both drafts are equally valid by default",
      "Always choose the longer draft regardless of content quality",
      "Always choose the first draft regardless of content quality",
    ]),
    correctOptionIds: ["a"],
    explanation: "Comparing outputs meaningfully means examining substantive differences (accuracy, tone, completeness) — not defaulting to length, order, or chance.",
  },

  // ───────────────────────── Domain 3: Product and Model Selection (10) ─────────────────────────
  {
    domain: 3,
    itemType: "single",
    stem: "A team wants to give Claude persistent access to their style guide, brand voice examples, and past campaign briefs so every conversation starts with that context already loaded. Which feature fits best?",
    options: opts([
      "A Project with custom instructions and uploaded knowledge sources",
      "A one-off chat conversation with no saved context",
      "An artifact with no attached files",
      "Research mode with web search only",
    ]),
    correctOptionIds: ["a"],
    explanation: "Projects are designed for exactly this: persistent instructions plus uploaded knowledge sources that every conversation within the project can draw on, instead of re-establishing context each time.",
  },
  {
    domain: 3,
    itemType: "single",
    stem: "A user needs Claude to pull together up-to-date information from multiple external sources to answer a broad, open-ended question. Which capability is best suited to this?",
    options: opts([
      "Research mode, which is designed to gather and synthesize information across sources",
      "A basic chat with no additional tools enabled",
      "An artifact, which is meant for standalone content rather than research synthesis",
      "Switching to the cheapest available model regardless of the task's needs",
    ]),
    correctOptionIds: ["a"],
    explanation: "Research-oriented product features are built for gathering and synthesizing information across sources — a plain chat or a content artifact isn't optimized for that kind of multi-source lookup.",
  },
  {
    domain: 3,
    itemType: "single",
    stem: "A company needs to triage thousands of short customer support tickets by category as cheaply and quickly as possible, where each classification task is simple. Which model tier best fits this?",
    options: opts([
      "A smaller, faster model (e.g., Haiku-tier), since the task is simple and volume/cost/speed matter most",
      "The largest, most capable model available, regardless of cost, since bigger is always better",
      "No model at all — the task should be done manually by staff",
      "A model chosen at random for each ticket",
    ]),
    correctOptionIds: ["a"],
    explanation: "Model selection should match task complexity to capability tier. High-volume, low-complexity classification is a good fit for smaller/faster/cheaper models rather than defaulting to the most capable (and most expensive) option.",
  },
  {
    domain: 3,
    itemType: "single",
    stem: "A strategy team needs Claude to synthesize a highly nuanced, ambiguous competitive analysis with significant judgment calls. Which model tier tradeoff is most appropriate?",
    options: opts([
      "A higher-capability model (e.g., Opus-tier), accepting higher cost/latency in exchange for stronger reasoning on ambiguous, high-stakes work",
      "The cheapest, fastest model available, since cost should always be minimized regardless of task complexity",
      "No model — nuanced judgment tasks are always a poor fit for any AI assistance",
      "A random model chosen without regard to the task's complexity",
    ]),
    correctOptionIds: ["a"],
    explanation: "For complex, ambiguous, high-stakes reasoning tasks, it's appropriate to accept more cost/latency for a more capable model — the 'always pick the cheapest' and 'always pick the most capable' rules are both oversimplifications; the right call depends on the task.",
  },
  {
    domain: 3,
    itemType: "single",
    stem: "A long-running conversation with Claude has grown so large that responses start losing track of details from early in the session. What's the best way to manage this?",
    options: opts([
      "Summarize the key context so far and start a fresh conversation (or persist it via a Project) rather than continuing indefinitely",
      "Keep adding more text to the same conversation forever, since context limits don't meaningfully affect quality",
      "Switch to a smaller model, which will remember more context than a larger one",
      "Delete all prior messages with no summary, losing the context entirely",
    ]),
    correctOptionIds: ["a"],
    explanation: "Managing context limits means proactively summarizing and restarting (or persisting key context in a Project/knowledge source) rather than letting a conversation grow indefinitely, which degrades output quality as earlier context gets crowded out.",
  },
  {
    domain: 3,
    itemType: "single",
    stem: "A user wants a piece of standalone, reusable content — like a formatted slide outline or a small interactive calculator — that they can view, edit, and export separately from the chat conversation. Which feature fits?",
    options: opts([
      "An artifact",
      "A plain inline chat reply with no structure",
      "Research mode",
      "Switching to a different, unrelated Project",
    ]),
    correctOptionIds: ["a"],
    explanation: "Artifacts are designed for standalone, reusable, viewable/editable content that lives outside the flow of conversation — ideal for outlines, documents, or small interactive tools.",
  },
  {
    domain: 3,
    itemType: "single",
    stem: "A budget-conscious startup needs Claude for both quick internal Slack replies (high volume, low stakes) and a small number of complex investor-facing analyses (low volume, high stakes). What's the most cost-effective model strategy?",
    options: opts([
      "Use a smaller/faster model for the Slack replies and a more capable model for the investor analyses",
      "Use the most expensive model for everything to guarantee consistency",
      "Use the cheapest model for everything, including the investor analyses",
      "Alternate randomly between model tiers regardless of task",
    ]),
    correctOptionIds: ["a"],
    explanation: "Matching model tier to task stakes and complexity — cheaper/faster for high-volume low-stakes work, more capable for high-stakes nuanced work — is the cost-effective approach rather than a single tier for everything.",
  },
  {
    domain: 3,
    itemType: "single",
    stem: "A Project's uploaded knowledge base has grown to include outdated pricing sheets alongside current ones, and Claude sometimes cites the wrong price. What's the best fix?",
    options: opts([
      "Remove or clearly label the outdated files in the Project's knowledge so only current information is referenced",
      "Add even more old pricing sheets to 'balance out' the confusion",
      "Ignore it, since Claude always automatically prefers the newest file with no help",
      "Switch to a different model tier, since model choice fixes stale-knowledge issues",
    ]),
    correctOptionIds: ["a"],
    explanation: "Conflicting or outdated knowledge sources need to be actively curated (removed or labeled) — this is a knowledge management issue, not something a different model tier resolves.",
  },
  {
    domain: 3,
    itemType: "single",
    stem: "A user is deciding whether to use a chat conversation or set up a Project for a task they'll repeat weekly with the same background materials. What's the better choice, and why?",
    options: opts([
      "A Project, because it persists instructions and files so the user doesn't have to re-upload/re-explain context every week",
      "A plain chat, because Projects can only be used once and then must be deleted",
      "A plain chat, because Projects cannot contain uploaded files",
      "Neither — recurring tasks with the same materials should never use Claude",
    ]),
    correctOptionIds: ["a"],
    explanation: "Projects exist specifically for recurring work with shared context — persisting instructions and knowledge avoids re-establishing the same setup in every new chat.",
  },
  {
    domain: 3,
    itemType: "single",
    stem: "A developer needs to decide between Haiku, Sonnet, and Opus tiers for an automated pipeline that drafts hundreds of short internal changelog entries daily. What should primarily drive the choice?",
    options: opts([
      "The complexity of the task relative to cost and speed needs — a simple, high-volume, low-stakes task favors a lighter/faster tier",
      "Always defaulting to Opus because it has the most name recognition",
      "Picking whichever model was mentioned most recently in the news",
      "Picking a tier at random since output quality doesn't vary by model",
    ]),
    correctOptionIds: ["a"],
    explanation: "Model selection should be driven by matching task complexity/stakes against cost and speed tradeoffs — not brand recognition or novelty, and quality does vary meaningfully across model tiers.",
  },

  // ───────────────────────── Domain 4: Workflow Integration and Solution Design (14) ─────────────────────────
  {
    domain: 4,
    itemType: "single",
    stem: "A department head wants to understand whether Claude is a good fit for automating their weekly reporting process. What's the first step in a solid solution-design approach?",
    options: opts([
      "Analyze the current requirements and workflow in detail to identify where Claude adds value versus where it doesn't",
      "Immediately roll Claude out company-wide without assessing the specific workflow",
      "Skip requirements analysis and let each employee decide individually with no shared process",
      "Assume Claude can replace the entire reporting process without any human involvement",
    ]),
    correctOptionIds: ["a"],
    explanation: "Requirements analysis — understanding the current workflow and where AI assistance genuinely helps — should come before rollout decisions, not after.",
  },
  {
    domain: 4,
    itemType: "single",
    stem: "A process improvement lead uses Claude to help identify bottlenecks in a customer onboarding workflow. What is this an example of?",
    options: opts([
      "Using Claude to support research, planning, and process optimization",
      "An inappropriate use of Claude, since process analysis should never involve AI",
      "Solution development, since bottleneck identification is the same as building a solution",
      "Governance and compliance work only",
    ]),
    correctOptionIds: ["a"],
    explanation: "Analyzing an existing process to find inefficiencies is a research/planning/process-optimization use case — one of the core task statements for workflow integration and solution design.",
  },
  {
    domain: 4,
    itemType: "single",
    stem: "A team has built a working prototype process using Claude to draft weekly client updates. What should happen before this becomes a permanent part of the workflow?",
    options: opts([
      "Iterate on the solution based on real usage and feedback, refining prompts/process before full adoption",
      "Immediately lock the process in place with zero changes allowed going forward",
      "Discard the prototype entirely regardless of how well it performed",
      "Skip any evaluation and roll it out to every team in the company at once",
    ]),
    correctOptionIds: ["a"],
    explanation: "Solution design is iterative — prototypes should be refined based on real feedback before broader rollout, rather than being locked in prematurely or scaled without validation.",
  },
  {
    domain: 4,
    itemType: "single",
    stem: "An operations team wants to integrate Claude into their existing ticketing system so agents can get draft responses without leaving their current tool. What best describes this goal?",
    options: opts([
      "Integrating Claude into an existing workflow rather than requiring a separate, disconnected process",
      "Replacing the ticketing system entirely with a brand-new one",
      "Avoiding any connection between Claude and existing tools",
      "Requiring agents to manually copy-paste between five different systems as a permanent solution",
    ]),
    correctOptionIds: ["a"],
    explanation: "Fitting Claude into where people already work — rather than bolting on a disconnected extra step — is the core idea of workflow integration.",
  },
  {
    domain: 4,
    itemType: "single",
    stem: "A product manager needs to explain to skeptical executives what Claude can and cannot reliably do for their team's use case. What should the pitch include?",
    options: opts([
      "A realistic picture of both the value Claude adds and its current limitations for this specific use case",
      "Only the benefits, omitting any limitations to make the pitch more persuasive",
      "Only the limitations, to avoid setting any expectations at all",
      "A generic pitch with no connection to the team's actual use case",
    ]),
    correctOptionIds: ["a"],
    explanation: "Communicating Claude's value and limitations honestly — grounded in the specific use case — builds credibility and sets realistic expectations, which overselling or underselling both undermine.",
  },
  {
    domain: 4,
    itemType: "multi",
    stem: "A consultant is scoping a new Claude-assisted workflow for a client's contract review process. Which two activities belong in the requirements-analysis phase? (Select 2)",
    options: opts([
      "Interviewing the legal team about current pain points and volume of contracts reviewed",
      "Identifying what 'good' review output looks like and any compliance constraints",
      "Immediately writing final prompts without any of the above",
      "Announcing the new process to the whole company before it's designed",
    ]),
    correctOptionIds: ["a", "b"],
    explanation: "Requirements analysis is about understanding stakeholder needs, current pain points, and constraints before designing a solution — not skipping straight to implementation or announcement.",
  },
  {
    domain: 4,
    itemType: "single",
    stem: "A retail company wants to use Claude to help plan next quarter's inventory strategy based on past sales trends. Which best characterizes this use case?",
    options: opts([
      "Supporting research and planning by synthesizing trends to inform (not replace) the final planning decision",
      "Fully automating inventory ordering with no human decision-maker involved",
      "An inappropriate use case that has nothing to do with workflow integration",
      "A governance and compliance exercise only",
    ]),
    correctOptionIds: ["a"],
    explanation: "This is a research/planning support use case — Claude helps synthesize trend data to inform human planning decisions, not a case where it should replace the decision-maker.",
  },
  {
    domain: 4,
    itemType: "single",
    stem: "A team's current workflow requires an employee to manually reformat Claude's output before sending it to a client, every single time, in the same predictable way. What's the best next step in solution design?",
    options: opts([
      "Adjust the prompt or template so Claude produces the target format directly, removing the repetitive manual step",
      "Accept the manual reformatting step forever since prompts cannot influence output format",
      "Stop using Claude for this task without investigating why the format doesn't match",
      "Add a second employee to do the same manual reformatting redundantly",
    ]),
    correctOptionIds: ["a"],
    explanation: "A predictable, repeated manual fix-up step is a signal the workflow (or prompt/template) should be redesigned to close that gap — not something to route more manual labor at.",
  },
  {
    domain: 4,
    itemType: "single",
    stem: "An IT team is deciding where Claude fits into a multi-step approval workflow that includes a legally required human sign-off. Where should Claude be positioned?",
    options: opts([
      "Assisting in drafting/preparing material for review, with the required human sign-off step kept intact",
      "Replacing the legally required human sign-off entirely",
      "Nowhere at all, since any legal requirement means AI can't be part of the workflow",
      "Positioned after the sign-off so it can override the human decision",
    ]),
    correctOptionIds: ["a"],
    explanation: "Good solution design respects hard constraints like legally required human sign-offs — Claude can assist earlier in the workflow without displacing a mandated human decision point.",
  },
  {
    domain: 4,
    itemType: "single",
    stem: "A nonprofit's program team wants Claude's help designing a new volunteer-matching process from scratch. What's a reasonable first deliverable from Claude in this solution-design effort?",
    options: opts([
      "A draft process outline and key decision points to discuss and refine with the team, not a finished, unreviewed system",
      "A final, unchangeable system implemented without any team input",
      "Nothing, since Claude cannot assist with process design at all",
      "A random workflow unrelated to volunteer matching",
    ]),
    correctOptionIds: ["a"],
    explanation: "Solution design is collaborative and iterative — a first draft to react to and refine is more realistic and useful than expecting (or delivering) a finished, unreviewed system in one step.",
  },
  {
    domain: 4,
    itemType: "single",
    stem: "A sales team wants to communicate to leadership that Claude cut their proposal drafting time in half, but still requires review before sending. How should this be framed?",
    options: opts([
      "As a meaningful efficiency gain with a clear remaining human-review step, not full automation",
      "As full automation with zero remaining human involvement",
      "As having no measurable value since review is still required",
      "Without mentioning the review step at all, to make the result sound more impressive",
    ]),
    correctOptionIds: ["a"],
    explanation: "Accurately communicating both the value (time savings) and the limitation (review still required) gives stakeholders a realistic picture — overstating automation or hiding the review step both misrepresent the workflow.",
  },
  {
    domain: 4,
    itemType: "single",
    stem: "A logistics company is piloting Claude for route-planning suggestions. Drivers report the suggestions are often good but occasionally impractical (e.g., ignoring a known road closure). What's the appropriate solution-design response?",
    options: opts([
      "Keep a human-in-the-loop review step for suggestions and feed recurring gaps (like road closures) back into the prompt/data as context",
      "Immediately cancel the pilot and never revisit AI-assisted route planning",
      "Remove the human review step to speed up adoption despite the known gaps",
      "Ignore driver feedback since Claude's suggestions are always correct",
    ]),
    correctOptionIds: ["a"],
    explanation: "Iterating on a solution based on real-world feedback — while keeping appropriate human review for a task with real-world safety/practicality stakes — is the right response, rather than abandoning or over-trusting the pilot.",
  },
  {
    domain: 4,
    itemType: "single",
    stem: "A company wants Claude to help draft internal training materials that will later be integrated into their LMS (learning management system). What's a key integration consideration?",
    options: opts([
      "Producing content in a format/structure compatible with the LMS's import requirements",
      "Ignoring the LMS's format entirely since integration doesn't matter",
      "Requiring the LMS to be replaced before any content can be drafted",
      "Avoiding any thought about downstream systems during drafting",
    ]),
    correctOptionIds: ["a"],
    explanation: "Workflow integration means considering how output will flow into existing downstream systems (like an LMS) so the work doesn't need to be redone or heavily reformatted later.",
  },
  {
    domain: 4,
    itemType: "single",
    stem: "A startup founder asks Claude to help design a customer feedback triage workflow. Claude proposes routing all feedback through itself with no human checkpoint, even for messages flagged as urgent complaints. What should the founder do?",
    options: opts([
      "Revise the design to add a human checkpoint for urgent/sensitive cases before finalizing the workflow",
      "Adopt the proposal exactly as given, since Claude's first design is optimal by default",
      "Reject using Claude for workflow design entirely going forward",
      "Remove all human involvement from customer feedback handling permanently",
    ]),
    correctOptionIds: ["a"],
    explanation: "Even a helpful draft workflow from Claude should be critically reviewed and adjusted — especially to insert human checkpoints for urgent or sensitive cases — rather than adopted uncritically or used as a reason to abandon the tool.",
  },

  // ───────────────────────── Domain 5: Configuration and Knowledge Management (10) ─────────────────────────
  {
    domain: 5,
    itemType: "single",
    stem: "A team is setting up a Project for customer support. What belongs in the Project's custom instructions?",
    options: opts([
      "Standing guidance Claude should follow every time: tone, escalation rules, formatting expectations for this Project's conversations",
      "The full text of every past support ticket, regardless of size",
      "Nothing — custom instructions are only used for artifacts, never for Projects",
      "A one-time request meant for a single conversation only",
    ]),
    correctOptionIds: ["a"],
    explanation: "Project-level custom instructions are for standing, reusable guidance that should apply across every conversation in the Project — not a dumping ground for raw data (that belongs in knowledge sources) or a one-off request.",
  },
  {
    domain: 5,
    itemType: "single",
    stem: "A marketing Project has a connector to the team's Google Drive folder. A teammate asks why Claude sometimes references an old, deprecated brand guideline. What is the most likely cause and fix?",
    options: opts([
      "The deprecated file is still present in the connected folder — remove or archive it out of the connected location",
      "Connectors always pull only the newest file automatically with no way to cause this issue",
      "Claude is hallucinating the entire guideline from nothing",
      "The fix is to disconnect Google Drive entirely and never use connectors",
    ]),
    correctOptionIds: ["a"],
    explanation: "Connectors surface whatever is actually present in the connected source — maintaining knowledge over time (removing outdated files) is the fix, not assuming the connector is broken or abandoning connectors altogether.",
  },
  {
    domain: 5,
    itemType: "single",
    stem: "A Project has two uploaded documents that give conflicting guidance on the company's refund policy. What should be done?",
    options: opts([
      "Resolve the conflict by removing or updating the outdated document so only accurate, current guidance remains",
      "Leave both documents in place and let Claude randomly pick one each time",
      "Delete all documents from the Project so there's no guidance at all",
      "Add a third, unrelated document to dilute the conflict",
    ]),
    correctOptionIds: ["a"],
    explanation: "Maintaining and updating configuration/knowledge over time — specifically resolving conflicting information — is a named responsibility in configuration and knowledge management; leaving the conflict unresolved risks inconsistent answers.",
  },
  {
    domain: 5,
    itemType: "single",
    stem: "A system-level instruction for a coding-assistant Project says: \"Always respond in valid, runnable Python 3 with type hints, and never include explanatory prose outside code comments.\" What is this an example of?",
    options: opts([
      "A well-scoped system-level instruction that sets clear, consistent behavioral constraints for the Project",
      "A knowledge source, since it's written as text",
      "An artifact configuration setting",
      "A one-time question rather than a standing instruction",
    ]),
    correctOptionIds: ["a"],
    explanation: "This is a system-level instruction: standing behavioral constraints (format, style, scope) that shape every response in that context, distinct from either a knowledge source or a single query.",
  },
  {
    domain: 5,
    itemType: "single",
    stem: "A Project's knowledge base is missing a key piece of information — the current fiscal year's budget caps — so Claude sometimes gives outdated or made-up figures when asked. What is the most direct fix?",
    options: opts([
      "Upload the current budget document to the Project's knowledge so Claude has an authoritative source to reference",
      "Ask Claude to guess the correct figures more confidently",
      "Switch to a different, unrelated Project instead of fixing the knowledge gap",
      "Do nothing, since missing knowledge always resolves itself automatically",
    ]),
    correctOptionIds: ["a"],
    explanation: "Missing knowledge is addressed by adding the authoritative source — this directly prevents the kind of fabricated/outdated answers described, rather than working around the Project or hoping the issue self-resolves.",
  },
  {
    domain: 5,
    itemType: "multi",
    stem: "Which two of the following are legitimate reasons to periodically review and update a Project's uploaded knowledge sources? (Select 2)",
    options: opts([
      "Some documents have become outdated since a policy or pricing change",
      "New reference material should be added to cover a gap Claude keeps stumbling on",
      "The Project has been open for more than a week, regardless of whether anything changed",
      "The knowledge folder currently has an even number of files",
    ]),
    correctOptionIds: ["a", "b"],
    explanation: "Knowledge maintenance should be driven by actual staleness or gaps — not arbitrary triggers like elapsed time or file count.",
  },
  {
    domain: 5,
    itemType: "single",
    stem: "An admin is setting up connectors for a Project that will help draft executive emails. Which practice best supports responsible knowledge management?",
    options: opts([
      "Connect only the specific folders/sources relevant to the task, rather than granting broad access to unrelated systems",
      "Connect every available data source in the company regardless of relevance",
      "Avoid documenting which sources are connected and why",
      "Never review connector access once it's set up",
    ]),
    correctOptionIds: ["a"],
    explanation: "Scoping connector access to what's actually relevant (least-privilege style thinking) is good practice for configuration and knowledge management, versus connecting everything indiscriminately.",
  },
  {
    domain: 5,
    itemType: "single",
    stem: "A user wants Claude's tone to always be formal and to always decline discussing competitor products by name, across every conversation in a given Project. Where should this be configured?",
    options: opts([
      "In the Project's custom instructions, since this is standing behavioral guidance that should apply broadly",
      "In a single chat message, to be re-typed at the start of every conversation",
      "Nowhere — behavior like this cannot be configured",
      "In the file name of an uploaded document",
    ]),
    correctOptionIds: ["a"],
    explanation: "Standing behavioral rules that should apply to every conversation belong in custom/system-level instructions at the Project level, not re-entered manually each time.",
  },
  {
    domain: 5,
    itemType: "single",
    stem: "Six months after a Project was set up, its custom instructions still reference a product name the company has since rebranded. What risk does this pose?",
    options: opts([
      "Claude may keep referencing the old product name, creating inconsistent or confusing outputs until the instructions are updated",
      "No risk at all, since custom instructions never affect output once set",
      "The rebrand will automatically propagate into the instructions with no manual update",
      "The Project will stop functioning entirely until it's deleted",
    ]),
    correctOptionIds: ["a"],
    explanation: "Configuration doesn't stay accurate on its own — stale instructions (like an old product name) keep influencing every output until someone updates them, which is why maintaining configs over time matters.",
  },
  {
    domain: 5,
    itemType: "single",
    stem: "A team lead wants new hires' Claude Projects to start with the same baseline instructions and reference documents as the rest of the team, without re-creating everything from scratch each time. What's a reasonable approach?",
    options: opts([
      "Maintain a documented, reusable baseline configuration (instructions + knowledge set) that can be applied consistently to new Projects",
      "Have each new hire freely invent their own instructions with no shared baseline",
      "Avoid giving any instructions to new hires' Projects at all",
      "Require new hires to memorize the instructions instead of configuring the Project",
    ]),
    correctOptionIds: ["a"],
    explanation: "A documented, reusable baseline configuration keeps Project setup consistent across a team and avoids everyone re-deriving instructions/knowledge from scratch.",
  },

  // ───────────────────────── Domain 6: Governance, Risk, and Responsible Use (13) ─────────────────────────
  {
    domain: 6,
    itemType: "single",
    stem: "An employee considers pasting a customer's unredacted medical record into Claude to ask for help summarizing it for an internal note. What's the primary concern?",
    options: opts([
      "Sharing sensitive personal health information may violate privacy regulations and company data-handling policy",
      "There is no concern, since summarizing is always a safe use case regardless of content",
      "The only concern is that the summary might be too short",
      "The only concern is grammar and tone of the record",
    ]),
    correctOptionIds: ["a"],
    explanation: "Sensitive categories of personal data (like health records) carry real regulatory and privacy obligations — the task (summarizing) doesn't neutralize the sensitivity of the underlying data being shared.",
  },
  {
    domain: 6,
    itemType: "single",
    stem: "A company's AI usage policy prohibits uploading unreleased financial results to third-party tools before the public earnings call. An employee wants Claude's help drafting talking points based on draft earnings figures. What should they do?",
    options: opts([
      "Follow the org's AI policy — avoid uploading the embargoed figures and use only information cleared for that purpose",
      "Upload the figures anyway since Claude is generally useful for financial writing",
      "Ignore the policy since it wasn't written with Claude specifically in mind",
      "Share the figures with a competitor to get a second opinion first",
    ]),
    correctOptionIds: ["a"],
    explanation: "Following organizational AI governance policy — including data restrictions like embargoed financials — takes precedence over general usefulness; the tool being helpful doesn't override a compliance restriction.",
  },
  {
    domain: 6,
    itemType: "single",
    stem: "A manager wants to use Claude to draft performance review language that will influence a promotion decision. What responsible-use consideration applies?",
    options: opts([
      "A human should critically review and take ownership of the final content, given the real impact on someone's career",
      "The manager can copy Claude's draft verbatim with zero review since it's just a formality",
      "This use case should be entirely automated with no human judgment involved",
      "There are no responsible-use considerations for internal HR content",
    ]),
    correctOptionIds: ["a"],
    explanation: "Decisions with real consequences for individuals — like promotion-relevant performance reviews — call for human ownership and review, not blind acceptance of an AI draft.",
  },
  {
    domain: 6,
    itemType: "single",
    stem: "A user wants Claude to help draft marketing copy that makes an unverifiable health claim about a supplement product to boost sales. What's the appropriate response to this request?",
    options: opts([
      "Decline or push back on making unverifiable/misleading claims, and suggest accurate, substantiated alternatives",
      "Comply fully since maximizing sales is always the top priority",
      "Comply but add a tiny disclaimer nobody will read",
      "Comply and also fabricate a supporting study to make the claim look credible",
    ]),
    correctOptionIds: ["a"],
    explanation: "Making unverifiable or misleading claims — especially about health — is an inappropriate use case with real ethical and potentially regulatory risk (e.g., FTC-type advertising rules); the responsible move is to avoid the claim and suggest substantiated alternatives.",
  },
  {
    domain: 6,
    itemType: "multi",
    stem: "Which two scenarios represent higher data-sensitivity risk when using Claude, requiring extra caution about what's shared? (Select 2)",
    options: opts([
      "Pasting a spreadsheet containing customers' Social Security numbers to ask for a formatting fix",
      "Sharing an unreleased M&A term sheet to get help polishing the prose",
      "Asking Claude to explain a public, publicly documented industry term",
      "Asking Claude for generic writing tips with no company data involved",
    ]),
    correctOptionIds: ["a", "b"],
    explanation: "Personally identifiable sensitive data (SSNs) and material nonpublic information (an unreleased M&A term sheet) both carry real regulatory/confidentiality risk — generic, non-sensitive requests don't carry the same risk profile.",
  },
  {
    domain: 6,
    itemType: "single",
    stem: "A government contractor's internal AI policy requires all AI-assisted work involving classified or export-controlled material to go through an approved, isolated tool — not general-purpose chat AI. An employee wants to use Claude anyway because it's faster. What should they do?",
    options: opts([
      "Follow the organization's governance policy and use the approved tool for that category of material",
      "Use Claude anyway since speed matters more than policy compliance",
      "Use Claude but avoid telling anyone about the classified content involved",
      "Ask Claude whether it thinks the policy is necessary and follow its answer",
    ]),
    correctOptionIds: ["a"],
    explanation: "Org AI policy governing sensitive material categories (classified, export-controlled) should be followed even when a general-purpose tool feels more convenient — governance policies like this typically exist for real regulatory/legal reasons.",
  },
  {
    domain: 6,
    itemType: "single",
    stem: "An employee asks Claude to help generate a list of employees' home addresses cross-referenced with a protected characteristic (e.g., a medical condition disclosed in an unrelated HR system) for an unspecified 'analysis.' What's the concern?",
    options: opts([
      "This combines sensitive personal and potentially protected-characteristic data in a way that raises serious privacy and discrimination risk",
      "There's no concern since the request is phrased as an 'analysis'",
      "The only concern is formatting the address list neatly",
      "This is a normal HR analytics request with no elevated risk",
    ]),
    correctOptionIds: ["a"],
    explanation: "Cross-referencing home addresses with protected health/characteristic data for an unclear purpose is a significant privacy and potential discrimination risk — the vague framing as 'analysis' doesn't reduce that risk.",
  },
  {
    domain: 6,
    itemType: "single",
    stem: "A teacher wants to use Claude to write individualized feedback on student essays, including students' names and grades. What governance consideration is most relevant?",
    options: opts([
      "Student education records are typically protected (e.g., under FERPA in the US) and should be handled per the school's data policy",
      "There is no relevant policy since teachers can share any student data freely",
      "The only consideration is whether the feedback is well-written",
      "Student names and grades are never considered sensitive information",
    ]),
    correctOptionIds: ["a"],
    explanation: "Student education records are a protected data category in many jurisdictions — appropriate use requires following the relevant privacy regulation and the school's own data-handling policy.",
  },
  {
    domain: 6,
    itemType: "single",
    stem: "A company is deciding whether a customer-facing chatbot built on Claude should be allowed to give binding legal advice about contract disputes without any human involved. What is the responsible-use conclusion?",
    options: opts([
      "This is likely an inappropriate use case for full automation given the legal/liability stakes — human oversight or a licensed professional should be involved",
      "This is a perfectly appropriate use case for full automation with no oversight",
      "The chatbot should give the advice but randomize it to avoid liability",
      "There is no meaningful risk difference between this and a simple FAQ chatbot",
    ]),
    correctOptionIds: ["a"],
    explanation: "High-stakes, regulated domains like binding legal advice generally require licensed human involvement — recognizing which use cases are and aren't appropriate for full automation is a core governance skill.",
  },
  {
    domain: 6,
    itemType: "single",
    stem: "An employee wants to know whether using Claude to draft internal meeting notes (no sensitive data, no external distribution) needs special approval under most reasonable org AI policies. What's the likely answer?",
    options: opts([
      "Likely low-risk and within normal appropriate use, though the org's specific policy should still be checked",
      "It always requires a legal review board regardless of content",
      "It's always prohibited under every possible AI policy",
      "It requires notifying regulators before use",
    ]),
    correctOptionIds: ["a"],
    explanation: "Low-sensitivity, internal-only use cases are typically lower-risk under most governance frameworks, though the specific org policy is always the actual source of truth rather than a blanket assumption.",
  },
  {
    domain: 6,
    itemType: "single",
    stem: "A user asks Claude to help brainstorm ways to word a layoff notice to minimize the company's legal exposure while being deliberately misleading to affected employees about the real reason. What's the ethical issue?",
    options: opts([
      "The request asks for deliberately deceptive communication designed to harm/mislead affected people, which is an inappropriate use case",
      "There is no ethical issue since legal exposure reduction is always a valid goal",
      "The only issue is tone, not the deception itself",
      "This is a completely standard HR communications request",
    ]),
    correctOptionIds: ["a"],
    explanation: "Deliberately misleading communication intended to harm or deceive affected individuals raises real ethical concerns, separate from and beyond ordinary legal risk-reduction in communications.",
  },
  {
    domain: 6,
    itemType: "single",
    stem: "A financial services firm operates under strict regulatory recordkeeping requirements. What governance step should be in place before broadly deploying Claude for client communications?",
    options: opts([
      "Confirm the deployment complies with applicable recordkeeping/compliance requirements (e.g., retaining communications as required)",
      "Deploy immediately with no compliance review, since AI tools are automatically exempt from recordkeeping rules",
      "Assume Claude handles all regulatory compliance automatically with no firm-side action needed",
      "Skip the review since the firm has used other software tools before",
    ]),
    correctOptionIds: ["a"],
    explanation: "Regulated industries need to confirm new tools fit within existing compliance obligations (like recordkeeping) before broad deployment — AI tools don't come with automatic regulatory exemptions.",
  },
  {
    domain: 6,
    itemType: "single",
    stem: "An employee in the EU wants to use Claude to process customer data for a new use case not covered by the company's existing privacy notice. What should happen first?",
    options: opts([
      "Check the new use case against applicable data protection requirements (e.g., GDPR) and update consent/notices if needed before proceeding",
      "Proceed immediately since existing privacy notices always cover any new use automatically",
      "Proceed and address any privacy concerns only if a regulator later asks",
      "Avoid asking anyone since asking might draw unwanted attention",
    ]),
    correctOptionIds: ["a"],
    explanation: "A new processing use case that falls outside existing notices/consent typically requires a privacy assessment and updated disclosures under regulations like GDPR — this should happen proactively, not reactively.",
  },

  // ───────────────────────── Domain 7: Troubleshooting and Optimisation (8) ─────────────────────────
  {
    domain: 7,
    itemType: "single",
    stem: "A user's prompt for summarizing meeting transcripts keeps producing summaries that miss action items entirely. What's the most targeted diagnosis?",
    options: opts([
      "The prompt likely doesn't explicitly ask for action items to be extracted, so Claude has no signal to prioritize them",
      "Claude is fundamentally incapable of identifying action items under any circumstances",
      "The transcripts must be corrupted, since prompt wording never affects what's included",
      "The issue is unrelated to the prompt and can only be fixed by switching accounts",
    ]),
    correctOptionIds: ["a"],
    explanation: "When an output consistently misses a specific element, the most likely cause is that the prompt doesn't explicitly request it — diagnosing underperformance starts with checking whether the ask was actually specified.",
  },
  {
    domain: 7,
    itemType: "single",
    stem: "A recurring weekly prompt used to work well but has started producing worse results after the source spreadsheet's column order changed. What's the most likely fix?",
    options: opts([
      "Update the prompt/template to reflect the new column order or reference columns by name instead of position",
      "Abandon the entire weekly process since one input format change means the tool no longer works",
      "Ignore the degraded output since prompt performance never depends on input structure",
      "Switch to an unrelated task entirely",
    ]),
    correctOptionIds: ["a"],
    explanation: "Troubleshooting a workflow regression starts by checking what changed upstream — here, adjusting the prompt to the new data structure (or referencing columns by name) directly addresses the root cause.",
  },
  {
    domain: 7,
    itemType: "single",
    stem: "After several rounds of feedback, a user still can't get Claude to produce the exact table format they want. What troubleshooting step is most likely to help?",
    options: opts([
      "Provide a concrete example of the exact desired table structure rather than describing it abstractly",
      "Stop giving any feedback and hope the next attempt is randomly correct",
      "Give up on structured output entirely, since tables can never be reliably produced",
      "Ask an unrelated question to reset the conversation without addressing the format issue",
    ]),
    correctOptionIds: ["a"],
    explanation: "When abstract descriptions aren't converging on the right format, providing a concrete example (few-shot) is a well-established, effective troubleshooting step.",
  },
  {
    domain: 7,
    itemType: "single",
    stem: "A team notices their Claude-assisted workflow takes longer than expected because every request re-explains the same background context. What's the most efficient optimization?",
    options: opts([
      "Move the recurring background context into a Project's custom instructions/knowledge so it doesn't need to be retyped each time",
      "Keep retyping the same context every time, since there's no way to reduce redundant work",
      "Remove all context going forward, even though it was necessary for good outputs",
      "Add even more redundant context to each request to be extra thorough",
    ]),
    correctOptionIds: ["a"],
    explanation: "Recognizing repeated, redundant setup as an efficiency problem — and moving it into persistent configuration — is a core workflow-optimization move.",
  },
  {
    domain: 7,
    itemType: "single",
    stem: "A user's multi-step prompt asks Claude to 'analyze, summarize, and recommend' all at once, and the output consistently shortchanges the recommendation section. What adjustment is most likely to help?",
    options: opts([
      "Split the request into separate, sequential prompts (or explicitly allocate space/priority to each part)",
      "Remove the recommendation request entirely instead of fixing the underlying issue",
      "Repeat the exact same combined prompt more times, expecting a different result",
      "Assume recommendations are a capability Claude fundamentally lacks",
    ]),
    correctOptionIds: ["a"],
    explanation: "When one part of a multi-part request consistently gets shortchanged, decomposing the task (or explicitly prioritizing/allocating space) tends to fix the imbalance — this is applying task decomposition as a troubleshooting fix.",
  },
  {
    domain: 7,
    itemType: "single",
    stem: "A support workflow using Claude has a high rate of responses that need heavy editing before being sent to customers. What's the best first optimization step?",
    options: opts([
      "Review a sample of edited-vs-original outputs to identify a specific recurring pattern (tone, missing info, format) and adjust the prompt/instructions accordingly",
      "Immediately abandon the workflow with no root-cause analysis",
      "Increase the volume of tickets routed through the same unchanged process",
      "Assume the issue is random and unfixable",
    ]),
    correctOptionIds: ["a"],
    explanation: "Effective troubleshooting starts with identifying the specific, recurring pattern behind the underperformance (via reviewing actual edits) before deciding what to change — not abandoning the process or assuming randomness.",
  },
  {
    domain: 7,
    itemType: "single",
    stem: "A user finds that breaking a long analysis prompt into two shorter prompts (first extract data points, then interpret them) produces noticeably better results than one long combined prompt. What should they do going forward?",
    options: opts([
      "Adopt the two-step approach as the new standard process for this kind of task",
      "Go back to the single combined prompt because it's fewer steps, regardless of quality",
      "Alternate randomly between the two approaches for no particular reason",
      "Conclude that both approaches are always identical in quality and effort doesn't matter",
    ]),
    correctOptionIds: ["a"],
    explanation: "Optimizing a workflow means adopting the approach shown to work better, even if it takes an extra step — efficiency should be measured by result quality and total effort, not just step count.",
  },
  {
    domain: 7,
    itemType: "single",
    stem: "A weekly reporting prompt that used to run smoothly now frequently gets cut off or truncated. The report's source data volume has grown substantially over the past few months. What's the most likely explanation to investigate first?",
    options: opts([
      "The growing input/output size may be approaching context or length limits, requiring the task to be chunked or summarized differently",
      "Claude has permanently lost the ability to generate long reports",
      "The truncation is unrelated to data volume and cannot be diagnosed",
      "The only fix is to stop generating reports altogether",
    ]),
    correctOptionIds: ["a"],
    explanation: "Truncation issues that emerge as data volume grows point toward context/length limits — the fix is adjusting the approach (chunking, summarizing, restructuring the request), which is a core troubleshooting and optimization skill.",
  },
];
